### ISSUE TITLE
Creation of 'lx' zone fails with 'zap'

### ISSUE THREAD

**Issue by bamdadkhan** [tribblix/overlays.lx#1]
Command executed:
`# zap create-zone -z BAALZLUX01 -t lx -x 10.10.10.120 -I /tmp/linux.iso`

Expected behaviour:
lx branded zone created.

Result:
```
**ERROR: lx not found - is it available?**
Usage: /usr/lib/zap/create-zone -z zone_name [-t whole|sparse|alien|s10]
  [-T template] [-I image_file]
  [-i ip_address] [-x ip_address] [-R ip_network/prefix]
  [-B] [-d extra_dir] [-o overlay] [-O overlay]
  [-S|-s shared_dir] [ -D dataset] [-U user]
  [-6] [-n number_of_zones]
  [-K action=arg[=arg...]]
```
Evidence that required packages are installed:
```
# zap search lx                                                       
Match: Uninstalled package TRIBdrv-net-emlxs in uninstalled overlay all-fabric-drivers
Match: Installed package TRIBdrv-net-elxl in uninstalled overlay all-network-drivers
Match: Installed package TRIBsys-zones-brand-lx in installed overlay base
Match: Installed package TRIBlxadm in installed overlay base
```

It seems even though the needed packages are installed, zap tools are unable to handle the 'lx' brand.

Reference for command used:
http://ptribble.blogspot.com/2017/07/running-lx-zones-with-tribblix.html

All the best,
bamdad

**Comment by ptribble** [comment]
Hm.

You must be running omnitribblix m20.6

It looks like the OmniOS developers changed the name of the zone brand recently. I think you can probably work around it for now by

cp /etc/zones/OMNIlx.xml /etc/zones/SUNWlx.xml

I'll fix the scripts for the next update.

Thanks for reporting this!
